# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be6c6c5e0bfbe2d0a1888be4c0c0e0763b5328b5f83c4382c320953c0a0c7ad7e441e6b2967cb4493a33f97b8e5dfaf4af8a26a1006d1e86852df3a00f3a76b1

test:
  secret_key_base: 6e4c5cbe184778709ca0d4eef18c54d1738674a67456269c80d627dce9222bdb8522a1a24adedde29d2a2f5634c12ec6667060c24ba984e745bbe0218ebc57a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
